portfolio/urls.py
from django.urls import path
from . import views

app_name = "portfolio"
urlpatterns = [
    path('', views.index, name='Home'),
    path('/contactme', views.contact, name='Contact')
]

schedulelist/urls.py
from django.urls import path

from . import views

app_name = 'schedulelist'

urlpatterns = [
    path('', views.index, name="kegiatan"),
    path('submit/', views.tambah, name="submit"),
    path('delete/<int:Kegiatan_id>/', views.deleteItem, name="delete")
]

story4/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('portfolio.urls')),
    path('schedule/', include('schedulelist.urls')),
]

portfolio/models.py
from django.db import models

# Create your models here.

schedulelist/models.py
from django.db import models
from django.utils import timezone
from datetime import datetime, date


class Kegiatan(models.Model):
    nama_kegiatan = models.CharField(max_length=20)
    tempat = models.CharField(max_length=20)
    tanggal = models.DateField('tanggal')
    waktu = models.TimeField('jam')
    kategori = models.CharField(max_length=20)

    def __str__(self):
        return self.nama_kegiatan

portfolio/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'index.html')


def contact(request):
    return render(request, 'contact.html')

schedulelist/views.py
from django.shortcuts import render, redirect

from .models import Kegiatan


def index(request):
    list_kegiatan = Kegiatan.objects.all()
    content = {
        "Kegiatan": list_kegiatan
    }

    return render(request, 'jadwal/index.html', content)


def tambah(request):
    data_kegiatan = request.POST.get('kegiatan')
    data_tempat = request.POST.get('tempat')
    data_tanggal = request.POST.get('tanggal')
    data_waktu = request.POST.get('waktu')
    data_kategori = request.POST.get('kategori')
    kegiatan_baru = Kegiatan(nama_kegiatan=data_kegiatan,
                             tempat=data_tempat, tanggal=data_tanggal, waktu=data_waktu, kategori=data_kategori)
    kegiatan_baru.save()
    return redirect('schedulelist:kegiatan')


def deleteItem(request, Kegiatan_id):
    item = Kegiatan.objects.get(id=Kegiatan_id)
    item.delete()
    return redirect('schedulelist:kegiatan')

portfolio/templates/contact.html
<!DOCTYPE html>
<html lang="en">
<!-- a -->

<head>
    {% load staticfiles %}
    <title>Contact</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style/style.css' static %}">
    <script src="https://kit.fontawesome.com/32cc3bf6b1.js" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="{% static 'parallax.min.js' %}"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
</head>

<body>
    <div class="landingPage" id="contactbg">
        <div class="nav justify-content-center">
            <div class="menu">
                <a href="{% url 'portfolio:Home' %}">done?</a>
            </div>
        </div>
        <section class="kotak" style="z-index: 2">
            <form>
                <div class="form-group">
                    <label for="exampleInputEmail1">Email</label>
                    <input type="email" class="form-control" id="emailinput" aria-describedby="emailHelp"
                        placeholder="Enter email">
                    <small id="emailHelp" class="form-text text-muted">Your email is safe with me ;).</small>
                </div>
                <div class="form-group">
                    <label for="exampleFormControlTextarea1">What's up?</label>
                    <textarea class="form-control" id="form" rows="5" placeholder="Anything is good."></textarea>
                </div>
                <button type="submit" class="btn btn-success">Submit</button>
            </form>
        </section>
    </div>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
    <script src="{% static 'app.js' %}"></script>
</body>

</html>

portfolio/templates/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load staticfiles %}
    <title>Mushaffa Huda</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'swiper.min.css' %}">
    <link rel="stylesheet" href="{% static 'style/style.css' %}">
    <script src="https://kit.fontawesome.com/32cc3bf6b1.js" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="{% static 'parallax.min.js' %}"></script>
    <meta name="viewport" content="width=device-width, inital-scale=1.0, shrink-to-fit=no" />
</head>

<body>
    <div class="landingPage" data-parallax="scroll" data-z-index="1" data-image-src="{% static 'images/image2.JPG' %}">
        <div class="nav justify-content-center">
            <div class="menu">
                <a href="#about">about</a>
                <a href="#projects">projects</a>
                <a href="#contact">contact</a>
                <a href="/schedule">schedule</a>
            </div>
        </div>
        <section class="ml-5" style="z-index: 2">
            <div class="desc">
                <div>
                    <h1 class="nama">Mushaffa Huda</h1>
                </div>
                <div class="shortDesc text-left">
                    <a>Software Engineer - Art Enthusiast</a>
                </div>
            </div>
        </section>
    </div>

    <section class="about" id="about">
        <div class="about-title text-center">
            <h2 class="sectionTitle">about.</h2>
        </div>
        <div class="about-page">
            <div>
                <section class="intro m-5">
                    <a class="header mr-3">
                        I am a Computer Science Undergrad Student at University Of Indonesia
                    </a>
                    <a class="introduction mt-4">
                        Technology have been my passion since i was little which led to my dream of pursuing my goal and
                        career in this Industry.
                    </a>
                    <a class="header mr-5 mt-5">
                        Background
                    </a>
                    <a class="mt-4">
                        Started with my love for programming i took upon myself a few basic website projects a few years
                        ago and found myself loving the abstraction and abnormality of what you call web development.
                        Ever since then, i have been doing projects that revine my skills as a developer and continue to
                        engage my knowledge in the IT world.
                    </a>
                    <a class="mt-4" style="font-weight: bold">
                        This led me to applying and studying as a Computer Science student at the best CS faculty in
                        Indonesia. Meeting new amazing people. and learning a lot about Computer Programming.
                    </a>
                </section>
            </div>
            <div>
                <a class="header ml-5">
                    Goals and Misc
                </a>
                <a class="ml-5 mt-4 mr-5">
                    Programming is not the only things im passionate about. i do a lot of Art and by alot i meant ALOT,
                    it helps me fill my boredom and my free time as well.
                </a>
                <a class="m-5">
                    i'm also doing some photography here and there, you could check it out. also check it out on my
                    vsco.
                    travelling is quite a hobby of mine as you can see from the background of this website (-w-).
                </a>
                <section class="gambar mr-5 ml-5">
                </section>
                <a class="ml-5 mt-4 mr-5" style="font-weight: bold; font-size: 14px;">
                    There are still a lot of things that i want to achieve and do in the future, and if you have your
                    own goals and dream and want to come together and discuss it with me, just hit me up. Coffee's on
                    me.
                </a>
            </div>
        </div>
    </section>
    <!-- halo -->
    <div class="projects" id="projects" data-parallax="scroll" data-image-src="{% static 'images/image1.JPG' %}">
        <section>
            <h1 class="projectTitle">Projects</h1>
        </section>
        <div class="swiper-container">
            <div class="swiper-wrapper">
                <div class="swiper-slide">
                    <div class="cardi">
                        <div class="sliderContent" id="compfestbg">
                            <!-- style="background: url(../images/compfestweb.png); background-size: contain;"> -->
                        </div>
                        <div class="content">
                            <p>
                                Participate in making the website of Compfest(Computer Festival) using React.js and
                                Django.
                            </p>
                            <button class="butn"
                                onclick="window.location.href='https://gitlab.com/compfest/black-manta'">Source
                                Code</button>
                        </div>
                    </div>
                </div>
                <div class="swiper-slide">
                    <div class="cardi">
                        <div class="sliderContent">
                        </div>
                        <div class="content">
                            <p>
                                A movie info website built using ajax and JQuery, and was utilizing the TMDb(the
                                moviedb)
                                api.
                            </p>
                            <button class="butn"
                                onclick="window.location.href='https://github.com/mhuda1/movieweb'">Source Code</button>
                        </div>
                    </div>
                </div>
                <div class="swiper-slide">
                    <div class="cardi">
                        <div class="sliderContent" id="jumpbg">
                            <!-- style="background: url(../images/plattygame.png); background-size: cover;"> -->
                        </div>
                        <div class="content">
                            <p>
                                A platformer game made using Pygame library in python3. This game utilizes many aspect
                                of essential platformer game component such as gravity and natural player movement. This
                                game was made in 48 hours.
                            </p>
                            <button class="butn"
                                onclick="window.location.href='https://github.com/mhuda1/Platty-Game'">Source
                                Code</button>
                        </div>
                    </div>
                </div>
                <div class="swiper-slide">
                    <div class="cardi">
                        <div class="sliderContent" id="ligtarbg">
                            <!-- style="background: url(../images/ligtar.png); background-size: cover;"> -->
                        </div>
                        <div class="content">
                            <p>
                                Website for Liga tari Krida Budaya Universitas Indonesia. Made using Laravel and
                                Bootstrap Framework.
                            </p>
                            <button class="butn"
                                onclick="window.location.href='https://github.com/bismitcrackers/Liga-Tari-UI'">Source
                                Code</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <section class="contactMe" id="contact">
        <div class="contact-page">
            <div class="animate">
                <section class="head m-5">
                    <a class="header mr-3"> If you want to collaborate or have a chat about anything - feel free to
                        contact
                        me
                    </a>
                    <a class="availnow mt-4">I am available for short term or long term projects.</a>
                </section>
                <section class="profile m-5">
                    <h3>Mushaffa Huda</h3>
                    <section class="info mt-4">
                        <a>Developer</a>
                        <a>
                            <mushaffahuda01@gmail class="com">mushaffahuda01@gmail.com</mushaffahuda01@gmail>
                        </a>
                        <a id="nomortelp">+62
                            877
                            8649 4132</a>
                    </section>
                </section>
                <section class="social ml-5">
                    <ul>
                        <li><a href=https://vsco.co/mhuda01/images/1> <i class="fa fa-camera"
                                aria-hidden="true"></i></a></li>
                        <li><a href=https://www.instagram.com/mhuda.1> <i class="fab fa-instagram"
                                aria-hidden="true"></i></a>
                        </li>
                        <li><a href=https://github.com/mhuda1> <i class="fab fa-github" aria-hidden="true"></i></a></li>
                        <li><a href=https://www.linkedin.com/in/mushaffa-huda-08b0b7180/> <i class="fab fa-linkedin-in"
                                aria-hidden="true"></i></a></li>
                    </ul>
                </section>
                <section class="inquire ml-5 mr-5 mt-5">
                    <a href="{% url 'portfolio:Contact' %}" style="font-size: 12px;">Or Here.</a>
                </section>
            </div>
        </div>
        <div class="contact-title text-center">
            <h2 class="sectionTitle text-left">Collaborate with me.</h2>
        </div>
    </section>

    <div class="bottom" data-parallax="scroll" data-z-index="1" data-image-src="{% static 'images/image0.JPG' %}">
        <h1 style="z-index: 2; font-size: 60px; font-weight: bold;">Bye.</h1>
    </div>

    <script src="{% static 'swiper.min.js' %}"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/ScrollMagic/2.0.7/ScrollMagic.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/ScrollMagic/2.0.7/plugins/debug.addIndicators.min.js"></script>
    <script src="{% static 'app.js' %}"></script>
</body>

</html>

schedulelist/templates/jadwal/index.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="UTF-8">
    <title>Jadwal Kegiatan</title>

    <!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <!-- materialize css -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">

    <!-- materialize js -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>

    <!-- let the browser know website is optimized for mobile -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
</head>

<body>


    <div class="container">
        <blockquote>
            <h3 class="">Jadwal~</h1>
        </blockquote>
    </div>

    <form action="{% url 'schedulelist:submit' %}" method="POST">
        {% csrf_token %}
        <div class="container">
            <div class="row">
                <div class="input-field col s8 m6 l6">
                    <input type="text" name="kegiatan" id="keg" class="validate" required>
                    <label for="keg">Nama Kegiatan</label>
                </div>
                <div class="input-field col s4 m6 l4">
                    <input type="text" name="kategori" id="kata" class="validate" required>
                    <label for="kata">Kategori</label>
                </div>
            </div>
            <div class="row">
                <div class="input-field col s6 m6 l4 ">
                    <input type="text" name="tempat" id="tpt" class="validate" required>
                    <label for="tpt">Tempat Kegiatan</label>
                </div>
                <div class="input-field col s3 m3 l2">
                    <input type="text" placeholder="Tanggal" class="datepicker" name="tanggal" required>
                </div>
                <div class="input-field col s3 m3 l2">
                    <input type="text" placeholder="Jam" class="timepicker" name="waktu" required>
                </div>
            </div>
            <div class="row">
                <div class="col s6">
                    <button class="btn waves-effect waves-light" type="submit" value="tambah">Tambah
                        <i class="material-icons right">send</i>
                    </button>

                </div>
            </div>
        </div>
    </form>

    <div class="divider"></div>

    {% for items in Kegiatan %}
    <div class="container">
        <form action="{% url 'schedulelist:delete' items.id %}" method="POST">
            {% csrf_token %}
            <div class="card-panel hoverable">
                <div class="card-content">
                    <span class="card-title">
                        <h5><strong>{{ items }}</strong><span class="new badge light-blue"
                                data-badge-caption="">{{ items.kategori }}</span></h5>
                    </span>
                    <p><i class="tiny material-icons">home</i> {{ items.tempat}}</p>
                    <p><i class="tiny material-icons">alarm</i> {{ items.tanggal}} {{ items.waktu }}</p>
                </div>
                <div class="card-action">
                    <button class="btn waves-effect waves-light red lighten-1" type="submit" name="action"
                        value="delete">Delete
                    </button>
                </div>
            </div>
        </form>
    </div>
    {% endfor %}

    <script>
        const Calender = document.querySelectorAll('.datepicker');
        const Jam = document.querySelectorAll('.timepicker');
        M.Datepicker.init(Calender, {
            format: 'yyyy-mm-dd',
            showClearBtn: true,
            i18n: {
                done: 'tambah',
                clear: 'hapus',
            }
        });
        M.Timepicker.init(Jam, {
            showClearBtn: true,
            i18n: {
                clear: 'hapus',
                done: 'tambah',
                cancel: 'cancel',
            }
        });
    </script>

</body>

</html>